DATASET:
  TRAIN_PATH: "dataset/fpv_yolo_manual_ds/train"
  TEST_PATH: "dataset/fpv_yolo_manual_ds/val"
  IMAGE_FORMAT: ".png"

SAM:
  CHECKPOINT: "./sam_vit_b_01ec64.pth"
  RANK: 512

TRAIN:
  BATCH_SIZE: 1
  NUM_EPOCHS: 50
  LEARNING_RATE: 1e-4